# Generated by Django 5.2 on 2025-04-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffstrack.country')),
                ('target', models.CharField(max_length=255)),
                ('first_announced', models.CharField(max_length=255)),
                ('date_in_effect', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
